name: testing

on:
  push:
    branches:
      - staging
      - production_test

jobs:
  collect-data:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, '/staging') && success()
    env:
      env_gh: "staging"
      id: 12345
    if: endsWith(github.ref, '/production_test') && success()
    env:
      env_gh: "production_test"
      id: 23456
    environment:
      name: ${{ env.env_gh }}
      url: "https://github.com"
    steps:
    - name: Check if variables/secrets are set correctly
      run: |
        touch "${GITHUB_WORKSPACE}/.env"
        echo "TEST=\"${{ secrets.APP_NAME }}\"" >> "${GITHUB_WORKSPACE}/.env"
        echo "ID=\"${{ env.ID }}\"" >> "${GITHUB_WORKSPACE}/.env"
        cat "${GITHUB_WORKSPACE}/.env"

