name: testing

on:
  push:
    branches:
      - staging
      - production_test

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env_name.outputs.env_name }}
    steps:
    - name: Set env name
      id: set_env_name
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "${BRANCH_NAME}"
        echo "::set-output name=env_name::${BRANCH_NAME}"
  collect-data:
    runs-on: ubuntu-latest
    env:
      staging: 12345
      production_test: 23456
    environment:
      name: ${{ needs.prep.outputs.env_name }}
      url: "https://github.com"
    steps:
    - name: Check if variables/secrets are set correctly
      run: |
        touch "${GITHUB_WORKSPACE}/.env"
        ID="${{ env.ID }}"
        echo "TEST=\"${{ secrets.APP_NAME }}\"" >> "${GITHUB_WORKSPACE}/.env"
        echo "ID=\"${!ID}\"" >> "${GITHUB_WORKSPACE}/.env"
        cat "${GITHUB_WORKSPACE}/.env"

